apiVersion: v1
kind: Service
metadata:
  name: preflight-api
  labels:
    app.kubernetes.io/name: preflight
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app: preflight-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
